package com.qfedu.daos;

import com.qfedu.pojos.CnActivity;
import com.qfedu.pojos.CnActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CnActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int countByExample(CnActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int deleteByExample(CnActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int deleteByPrimaryKey(String cnActivityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int insert(CnActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int insertSelective(CnActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    List<CnActivity> selectByExampleWithBLOBs(CnActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    List<CnActivity> selectByExample(CnActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    CnActivity selectByPrimaryKey(String cnActivityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") CnActivity record, @Param("example") CnActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CnActivity record, @Param("example") CnActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExample(@Param("record") CnActivity record, @Param("example") CnActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKeySelective(CnActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CnActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKey(CnActivity record);
}