package com.qfedu.daos;

import com.qfedu.pojos.CnActivityStatus;
import com.qfedu.pojos.CnActivityStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CnActivityStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int countByExample(CnActivityStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int deleteByExample(CnActivityStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int deleteByPrimaryKey(String cnActivityStatusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int insert(CnActivityStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int insertSelective(CnActivityStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    List<CnActivityStatus> selectByExample(CnActivityStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    CnActivityStatus selectByPrimaryKey(String cnActivityStatusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") CnActivityStatus record, @Param("example") CnActivityStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExample(@Param("record") CnActivityStatus record, @Param("example") CnActivityStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKeySelective(CnActivityStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_activity_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKey(CnActivityStatus record);
}