package com.qfedu.daos;

import com.qfedu.pojos.CnNoteStatus;
import com.qfedu.pojos.CnNoteStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CnNoteStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int countByExample(CnNoteStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int deleteByExample(CnNoteStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int deleteByPrimaryKey(String cnNoteStatusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int insert(CnNoteStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int insertSelective(CnNoteStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    List<CnNoteStatus> selectByExample(CnNoteStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    CnNoteStatus selectByPrimaryKey(String cnNoteStatusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") CnNoteStatus record, @Param("example") CnNoteStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExample(@Param("record") CnNoteStatus record, @Param("example") CnNoteStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKeySelective(CnNoteStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_status
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKey(CnNoteStatus record);
}