package com.qfedu.daos;

import com.qfedu.pojos.CnNote;
import com.qfedu.pojos.CnNoteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CnNoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int countByExample(CnNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int deleteByExample(CnNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int deleteByPrimaryKey(String cnNoteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int insert(CnNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int insertSelective(CnNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    List<CnNote> selectByExampleWithBLOBs(CnNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    List<CnNote> selectByExample(CnNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    CnNote selectByPrimaryKey(String cnNoteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") CnNote record, @Param("example") CnNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CnNote record, @Param("example") CnNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExample(@Param("record") CnNote record, @Param("example") CnNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKeySelective(CnNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CnNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKey(CnNote record);
}