package com.qfedu.daos;

import com.qfedu.pojos.CnNoteActivity;
import com.qfedu.pojos.CnNoteActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CnNoteActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int countByExample(CnNoteActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int deleteByExample(CnNoteActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int deleteByPrimaryKey(String cnNoteActivityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int insert(CnNoteActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int insertSelective(CnNoteActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    List<CnNoteActivity> selectByExampleWithBLOBs(CnNoteActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    List<CnNoteActivity> selectByExample(CnNoteActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    CnNoteActivity selectByPrimaryKey(String cnNoteActivityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") CnNoteActivity record, @Param("example") CnNoteActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CnNoteActivity record, @Param("example") CnNoteActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExample(@Param("record") CnNoteActivity record, @Param("example") CnNoteActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKeySelective(CnNoteActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CnNoteActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_note_activity
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKey(CnNoteActivity record);
}