package com.qfedu.daos;

import com.qfedu.pojos.CnNotebook;
import com.qfedu.pojos.CnNotebookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CnNotebookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int countByExample(CnNotebookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int deleteByExample(CnNotebookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int deleteByPrimaryKey(String cnNotebookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int insert(CnNotebook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int insertSelective(CnNotebook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    List<CnNotebook> selectByExampleWithBLOBs(CnNotebookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    List<CnNotebook> selectByExample(CnNotebookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    CnNotebook selectByPrimaryKey(String cnNotebookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") CnNotebook record, @Param("example") CnNotebookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CnNotebook record, @Param("example") CnNotebookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExample(@Param("record") CnNotebook record, @Param("example") CnNotebookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKeySelective(CnNotebook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CnNotebook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_notebook
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKey(CnNotebook record);
}