package com.qfedu.daos;

import com.qfedu.pojos.CnShare;
import com.qfedu.pojos.CnShareExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CnShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_share
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int countByExample(CnShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_share
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int deleteByExample(CnShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_share
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int deleteByPrimaryKey(String cnShareId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_share
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int insert(CnShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_share
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int insertSelective(CnShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_share
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    List<CnShare> selectByExampleWithBLOBs(CnShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_share
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    List<CnShare> selectByExample(CnShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_share
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    CnShare selectByPrimaryKey(String cnShareId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_share
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") CnShare record, @Param("example") CnShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_share
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CnShare record, @Param("example") CnShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_share
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByExample(@Param("record") CnShare record, @Param("example") CnShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_share
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKeySelective(CnShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_share
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CnShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cn_share
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    int updateByPrimaryKey(CnShare record);
}