package com.qfedu.pojos;

public class CnActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_activity.cn_activity_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnActivityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_activity.cn_activity_title
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnActivityTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_activity.cn_activity_end_time
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private Long cnActivityEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_activity.cn_activity_body
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnActivityBody;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_activity.cn_activity_id
     *
     * @return the value of cn_activity.cn_activity_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnActivityId() {
        return cnActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_activity.cn_activity_id
     *
     * @param cnActivityId the value for cn_activity.cn_activity_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnActivityId(String cnActivityId) {
        this.cnActivityId = cnActivityId == null ? null : cnActivityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_activity.cn_activity_title
     *
     * @return the value of cn_activity.cn_activity_title
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnActivityTitle() {
        return cnActivityTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_activity.cn_activity_title
     *
     * @param cnActivityTitle the value for cn_activity.cn_activity_title
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnActivityTitle(String cnActivityTitle) {
        this.cnActivityTitle = cnActivityTitle == null ? null : cnActivityTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_activity.cn_activity_end_time
     *
     * @return the value of cn_activity.cn_activity_end_time
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public Long getCnActivityEndTime() {
        return cnActivityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_activity.cn_activity_end_time
     *
     * @param cnActivityEndTime the value for cn_activity.cn_activity_end_time
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnActivityEndTime(Long cnActivityEndTime) {
        this.cnActivityEndTime = cnActivityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_activity.cn_activity_body
     *
     * @return the value of cn_activity.cn_activity_body
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnActivityBody() {
        return cnActivityBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_activity.cn_activity_body
     *
     * @param cnActivityBody the value for cn_activity.cn_activity_body
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnActivityBody(String cnActivityBody) {
        this.cnActivityBody = cnActivityBody == null ? null : cnActivityBody.trim();
    }
}