package com.qfedu.pojos;

public class CnActivityStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_activity_status.cn_activity_status_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnActivityStatusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_activity_status.cn_activity_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnActivityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_activity_status.cn_activity_status_code
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnActivityStatusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_activity_status.cn_activity_status_name
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnActivityStatusName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_activity_status.cn_activity_status_id
     *
     * @return the value of cn_activity_status.cn_activity_status_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnActivityStatusId() {
        return cnActivityStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_activity_status.cn_activity_status_id
     *
     * @param cnActivityStatusId the value for cn_activity_status.cn_activity_status_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnActivityStatusId(String cnActivityStatusId) {
        this.cnActivityStatusId = cnActivityStatusId == null ? null : cnActivityStatusId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_activity_status.cn_activity_id
     *
     * @return the value of cn_activity_status.cn_activity_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnActivityId() {
        return cnActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_activity_status.cn_activity_id
     *
     * @param cnActivityId the value for cn_activity_status.cn_activity_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnActivityId(String cnActivityId) {
        this.cnActivityId = cnActivityId == null ? null : cnActivityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_activity_status.cn_activity_status_code
     *
     * @return the value of cn_activity_status.cn_activity_status_code
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnActivityStatusCode() {
        return cnActivityStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_activity_status.cn_activity_status_code
     *
     * @param cnActivityStatusCode the value for cn_activity_status.cn_activity_status_code
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnActivityStatusCode(String cnActivityStatusCode) {
        this.cnActivityStatusCode = cnActivityStatusCode == null ? null : cnActivityStatusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_activity_status.cn_activity_status_name
     *
     * @return the value of cn_activity_status.cn_activity_status_name
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnActivityStatusName() {
        return cnActivityStatusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_activity_status.cn_activity_status_name
     *
     * @param cnActivityStatusName the value for cn_activity_status.cn_activity_status_name
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnActivityStatusName(String cnActivityStatusName) {
        this.cnActivityStatusName = cnActivityStatusName == null ? null : cnActivityStatusName.trim();
    }
}