package com.qfedu.pojos;

public class CnNotebookType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_notebook_type.cn_notebook_type_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNotebookTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_notebook_type.cn_notebook_type_code
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNotebookTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_notebook_type.cn_notebook_type_name
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNotebookTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_notebook_type.cn_notebook_type_desc
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNotebookTypeDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_notebook_type.cn_notebook_type_id
     *
     * @return the value of cn_notebook_type.cn_notebook_type_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNotebookTypeId() {
        return cnNotebookTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_notebook_type.cn_notebook_type_id
     *
     * @param cnNotebookTypeId the value for cn_notebook_type.cn_notebook_type_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNotebookTypeId(String cnNotebookTypeId) {
        this.cnNotebookTypeId = cnNotebookTypeId == null ? null : cnNotebookTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_notebook_type.cn_notebook_type_code
     *
     * @return the value of cn_notebook_type.cn_notebook_type_code
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNotebookTypeCode() {
        return cnNotebookTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_notebook_type.cn_notebook_type_code
     *
     * @param cnNotebookTypeCode the value for cn_notebook_type.cn_notebook_type_code
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNotebookTypeCode(String cnNotebookTypeCode) {
        this.cnNotebookTypeCode = cnNotebookTypeCode == null ? null : cnNotebookTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_notebook_type.cn_notebook_type_name
     *
     * @return the value of cn_notebook_type.cn_notebook_type_name
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNotebookTypeName() {
        return cnNotebookTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_notebook_type.cn_notebook_type_name
     *
     * @param cnNotebookTypeName the value for cn_notebook_type.cn_notebook_type_name
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNotebookTypeName(String cnNotebookTypeName) {
        this.cnNotebookTypeName = cnNotebookTypeName == null ? null : cnNotebookTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_notebook_type.cn_notebook_type_desc
     *
     * @return the value of cn_notebook_type.cn_notebook_type_desc
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNotebookTypeDesc() {
        return cnNotebookTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_notebook_type.cn_notebook_type_desc
     *
     * @param cnNotebookTypeDesc the value for cn_notebook_type.cn_notebook_type_desc
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNotebookTypeDesc(String cnNotebookTypeDesc) {
        this.cnNotebookTypeDesc = cnNotebookTypeDesc == null ? null : cnNotebookTypeDesc.trim();
    }
}