package com.qfedu.pojos;

public class CnNote {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_note_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_notebook_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNotebookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_user_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_note_status_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteStatusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_note_type_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_note_title
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_note_create_time
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private Long cnNoteCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_note_last_modify_time
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private Long cnNoteLastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note.cn_note_body
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteBody;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_note_id
     *
     * @return the value of cn_note.cn_note_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteId() {
        return cnNoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_note_id
     *
     * @param cnNoteId the value for cn_note.cn_note_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteId(String cnNoteId) {
        this.cnNoteId = cnNoteId == null ? null : cnNoteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_notebook_id
     *
     * @return the value of cn_note.cn_notebook_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNotebookId() {
        return cnNotebookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_notebook_id
     *
     * @param cnNotebookId the value for cn_note.cn_notebook_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNotebookId(String cnNotebookId) {
        this.cnNotebookId = cnNotebookId == null ? null : cnNotebookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_user_id
     *
     * @return the value of cn_note.cn_user_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnUserId() {
        return cnUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_user_id
     *
     * @param cnUserId the value for cn_note.cn_user_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnUserId(String cnUserId) {
        this.cnUserId = cnUserId == null ? null : cnUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_note_status_id
     *
     * @return the value of cn_note.cn_note_status_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteStatusId() {
        return cnNoteStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_note_status_id
     *
     * @param cnNoteStatusId the value for cn_note.cn_note_status_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteStatusId(String cnNoteStatusId) {
        this.cnNoteStatusId = cnNoteStatusId == null ? null : cnNoteStatusId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_note_type_id
     *
     * @return the value of cn_note.cn_note_type_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteTypeId() {
        return cnNoteTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_note_type_id
     *
     * @param cnNoteTypeId the value for cn_note.cn_note_type_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteTypeId(String cnNoteTypeId) {
        this.cnNoteTypeId = cnNoteTypeId == null ? null : cnNoteTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_note_title
     *
     * @return the value of cn_note.cn_note_title
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteTitle() {
        return cnNoteTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_note_title
     *
     * @param cnNoteTitle the value for cn_note.cn_note_title
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteTitle(String cnNoteTitle) {
        this.cnNoteTitle = cnNoteTitle == null ? null : cnNoteTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_note_create_time
     *
     * @return the value of cn_note.cn_note_create_time
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public Long getCnNoteCreateTime() {
        return cnNoteCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_note_create_time
     *
     * @param cnNoteCreateTime the value for cn_note.cn_note_create_time
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteCreateTime(Long cnNoteCreateTime) {
        this.cnNoteCreateTime = cnNoteCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_note_last_modify_time
     *
     * @return the value of cn_note.cn_note_last_modify_time
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public Long getCnNoteLastModifyTime() {
        return cnNoteLastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_note_last_modify_time
     *
     * @param cnNoteLastModifyTime the value for cn_note.cn_note_last_modify_time
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteLastModifyTime(Long cnNoteLastModifyTime) {
        this.cnNoteLastModifyTime = cnNoteLastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note.cn_note_body
     *
     * @return the value of cn_note.cn_note_body
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteBody() {
        return cnNoteBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note.cn_note_body
     *
     * @param cnNoteBody the value for cn_note.cn_note_body
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteBody(String cnNoteBody) {
        this.cnNoteBody = cnNoteBody == null ? null : cnNoteBody.trim();
    }
}