package com.qfedu.pojos;

public class CnNoteStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note_status.cn_note_status_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteStatusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note_status.cn_note_status_code
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteStatusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note_status.cn_note_status_name
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteStatusName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note_status.cn_note_status_id
     *
     * @return the value of cn_note_status.cn_note_status_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteStatusId() {
        return cnNoteStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note_status.cn_note_status_id
     *
     * @param cnNoteStatusId the value for cn_note_status.cn_note_status_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteStatusId(String cnNoteStatusId) {
        this.cnNoteStatusId = cnNoteStatusId == null ? null : cnNoteStatusId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note_status.cn_note_status_code
     *
     * @return the value of cn_note_status.cn_note_status_code
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteStatusCode() {
        return cnNoteStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note_status.cn_note_status_code
     *
     * @param cnNoteStatusCode the value for cn_note_status.cn_note_status_code
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteStatusCode(String cnNoteStatusCode) {
        this.cnNoteStatusCode = cnNoteStatusCode == null ? null : cnNoteStatusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note_status.cn_note_status_name
     *
     * @return the value of cn_note_status.cn_note_status_name
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteStatusName() {
        return cnNoteStatusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note_status.cn_note_status_name
     *
     * @param cnNoteStatusName the value for cn_note_status.cn_note_status_name
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteStatusName(String cnNoteStatusName) {
        this.cnNoteStatusName = cnNoteStatusName == null ? null : cnNoteStatusName.trim();
    }
}