package com.qfedu.pojos;

public class CnNoteActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note_activity.cn_note_activity_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteActivityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note_activity.cn_activity_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnActivityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note_activity.cn_note_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note_activity.cn_note_activity_up
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private Integer cnNoteActivityUp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note_activity.cn_note_activity_down
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private Integer cnNoteActivityDown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note_activity.cn_note_activity_title
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteActivityTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note_activity.cn_note_activity_body
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteActivityBody;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note_activity.cn_note_activity_id
     *
     * @return the value of cn_note_activity.cn_note_activity_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteActivityId() {
        return cnNoteActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note_activity.cn_note_activity_id
     *
     * @param cnNoteActivityId the value for cn_note_activity.cn_note_activity_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteActivityId(String cnNoteActivityId) {
        this.cnNoteActivityId = cnNoteActivityId == null ? null : cnNoteActivityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note_activity.cn_activity_id
     *
     * @return the value of cn_note_activity.cn_activity_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnActivityId() {
        return cnActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note_activity.cn_activity_id
     *
     * @param cnActivityId the value for cn_note_activity.cn_activity_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnActivityId(String cnActivityId) {
        this.cnActivityId = cnActivityId == null ? null : cnActivityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note_activity.cn_note_id
     *
     * @return the value of cn_note_activity.cn_note_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteId() {
        return cnNoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note_activity.cn_note_id
     *
     * @param cnNoteId the value for cn_note_activity.cn_note_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteId(String cnNoteId) {
        this.cnNoteId = cnNoteId == null ? null : cnNoteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note_activity.cn_note_activity_up
     *
     * @return the value of cn_note_activity.cn_note_activity_up
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public Integer getCnNoteActivityUp() {
        return cnNoteActivityUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note_activity.cn_note_activity_up
     *
     * @param cnNoteActivityUp the value for cn_note_activity.cn_note_activity_up
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteActivityUp(Integer cnNoteActivityUp) {
        this.cnNoteActivityUp = cnNoteActivityUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note_activity.cn_note_activity_down
     *
     * @return the value of cn_note_activity.cn_note_activity_down
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public Integer getCnNoteActivityDown() {
        return cnNoteActivityDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note_activity.cn_note_activity_down
     *
     * @param cnNoteActivityDown the value for cn_note_activity.cn_note_activity_down
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteActivityDown(Integer cnNoteActivityDown) {
        this.cnNoteActivityDown = cnNoteActivityDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note_activity.cn_note_activity_title
     *
     * @return the value of cn_note_activity.cn_note_activity_title
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteActivityTitle() {
        return cnNoteActivityTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note_activity.cn_note_activity_title
     *
     * @param cnNoteActivityTitle the value for cn_note_activity.cn_note_activity_title
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteActivityTitle(String cnNoteActivityTitle) {
        this.cnNoteActivityTitle = cnNoteActivityTitle == null ? null : cnNoteActivityTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note_activity.cn_note_activity_body
     *
     * @return the value of cn_note_activity.cn_note_activity_body
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteActivityBody() {
        return cnNoteActivityBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note_activity.cn_note_activity_body
     *
     * @param cnNoteActivityBody the value for cn_note_activity.cn_note_activity_body
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteActivityBody(String cnNoteActivityBody) {
        this.cnNoteActivityBody = cnNoteActivityBody == null ? null : cnNoteActivityBody.trim();
    }
}