package com.qfedu.pojos;

public class CnNoteType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note_type.cn_note_type_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note_type.cn_note_type_code
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note_type.cn_note_type_name
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_note_type.cn_note_type_desc
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteTypeDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note_type.cn_note_type_id
     *
     * @return the value of cn_note_type.cn_note_type_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteTypeId() {
        return cnNoteTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note_type.cn_note_type_id
     *
     * @param cnNoteTypeId the value for cn_note_type.cn_note_type_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteTypeId(String cnNoteTypeId) {
        this.cnNoteTypeId = cnNoteTypeId == null ? null : cnNoteTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note_type.cn_note_type_code
     *
     * @return the value of cn_note_type.cn_note_type_code
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteTypeCode() {
        return cnNoteTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note_type.cn_note_type_code
     *
     * @param cnNoteTypeCode the value for cn_note_type.cn_note_type_code
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteTypeCode(String cnNoteTypeCode) {
        this.cnNoteTypeCode = cnNoteTypeCode == null ? null : cnNoteTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note_type.cn_note_type_name
     *
     * @return the value of cn_note_type.cn_note_type_name
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteTypeName() {
        return cnNoteTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note_type.cn_note_type_name
     *
     * @param cnNoteTypeName the value for cn_note_type.cn_note_type_name
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteTypeName(String cnNoteTypeName) {
        this.cnNoteTypeName = cnNoteTypeName == null ? null : cnNoteTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_note_type.cn_note_type_desc
     *
     * @return the value of cn_note_type.cn_note_type_desc
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteTypeDesc() {
        return cnNoteTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_note_type.cn_note_type_desc
     *
     * @param cnNoteTypeDesc the value for cn_note_type.cn_note_type_desc
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteTypeDesc(String cnNoteTypeDesc) {
        this.cnNoteTypeDesc = cnNoteTypeDesc == null ? null : cnNoteTypeDesc.trim();
    }
}