package com.qfedu.pojos;

public class CnShare {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_share.cn_share_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnShareId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_share.cn_share_title
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnShareTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_share.cn_note_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnNoteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_share.cn_share_body
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnShareBody;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_share.cn_share_id
     *
     * @return the value of cn_share.cn_share_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnShareId() {
        return cnShareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_share.cn_share_id
     *
     * @param cnShareId the value for cn_share.cn_share_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnShareId(String cnShareId) {
        this.cnShareId = cnShareId == null ? null : cnShareId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_share.cn_share_title
     *
     * @return the value of cn_share.cn_share_title
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnShareTitle() {
        return cnShareTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_share.cn_share_title
     *
     * @param cnShareTitle the value for cn_share.cn_share_title
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnShareTitle(String cnShareTitle) {
        this.cnShareTitle = cnShareTitle == null ? null : cnShareTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_share.cn_note_id
     *
     * @return the value of cn_share.cn_note_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnNoteId() {
        return cnNoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_share.cn_note_id
     *
     * @param cnNoteId the value for cn_share.cn_note_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnNoteId(String cnNoteId) {
        this.cnNoteId = cnNoteId == null ? null : cnNoteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_share.cn_share_body
     *
     * @return the value of cn_share.cn_share_body
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnShareBody() {
        return cnShareBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_share.cn_share_body
     *
     * @param cnShareBody the value for cn_share.cn_share_body
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnShareBody(String cnShareBody) {
        this.cnShareBody = cnShareBody == null ? null : cnShareBody.trim();
    }
}