package com.qfedu.pojos;

public class CnUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_user.cn_user_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_user.cn_user_name
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_user.cn_user_password
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnUserPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_user.cn_user_token
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnUserToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cn_user.cn_user_nick
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    private String cnUserNick;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_user.cn_user_id
     *
     * @return the value of cn_user.cn_user_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnUserId() {
        return cnUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_user.cn_user_id
     *
     * @param cnUserId the value for cn_user.cn_user_id
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnUserId(String cnUserId) {
        this.cnUserId = cnUserId == null ? null : cnUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_user.cn_user_name
     *
     * @return the value of cn_user.cn_user_name
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnUserName() {
        return cnUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_user.cn_user_name
     *
     * @param cnUserName the value for cn_user.cn_user_name
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnUserName(String cnUserName) {
        this.cnUserName = cnUserName == null ? null : cnUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_user.cn_user_password
     *
     * @return the value of cn_user.cn_user_password
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnUserPassword() {
        return cnUserPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_user.cn_user_password
     *
     * @param cnUserPassword the value for cn_user.cn_user_password
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnUserPassword(String cnUserPassword) {
        this.cnUserPassword = cnUserPassword == null ? null : cnUserPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_user.cn_user_token
     *
     * @return the value of cn_user.cn_user_token
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnUserToken() {
        return cnUserToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_user.cn_user_token
     *
     * @param cnUserToken the value for cn_user.cn_user_token
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnUserToken(String cnUserToken) {
        this.cnUserToken = cnUserToken == null ? null : cnUserToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cn_user.cn_user_nick
     *
     * @return the value of cn_user.cn_user_nick
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public String getCnUserNick() {
        return cnUserNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cn_user.cn_user_nick
     *
     * @param cnUserNick the value for cn_user.cn_user_nick
     *
     * @mbggenerated Mon Jun 10 00:54:51 CST 2019
     */
    public void setCnUserNick(String cnUserNick) {
        this.cnUserNick = cnUserNick == null ? null : cnUserNick.trim();
    }
}